import pandas as pd
import yfinance as yf
import json

msft = yf.Ticker("MSFT")

# get stock info
# print(msft.info)

# get historical market data
hist_final = msft.history(interval="1m", start = "2020-05-15", end = "2020-05-20")
hist_final['Symbol'] = 'MSFT'
# print("Records till date: ")
# print(hist_final.tail(20))

# sym_list = [A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,ADI,ADM,ADP,ADS,ADSK,AEE,AEP,AES,AFL,AGN,AIG,AIZ,AJG,AKAM,ALB,ALGN,ALK,ALL,ALLE,ALXN,AMAT,AMCR,AMD,AME,AMGN,AMP,AMT,AMZN,ANET,ANSS,ANTM,AON,AOS,APA,APD,APH,APTV,ARNC,ATO,ATVI,AVGO,AVY,AWK,AXP,AZO,BA,BAC,BAX,BBY,BDX,BEN,BIIB,BK,BKNG,BKR,BLK,BLL,BMY,BR,BSX,BWA,C,CAG,CAH,CAT,CB,CBOE,CBRE,CCI,CCL,CDNS,CDW,CE,CERN,CF,CFG,CHD,CHRW,CHTR,CI,CL,CLX,CMA,CMCSA,CME,CMG,CMI,CMS,CNC,CNP,COF,COG,COO,COP,COST,COTY,CPB,CPRI,CPRT,CRM,CSCO,CSX,CTAS,CTL,CTSH,CTXS,CVS,CVX,CXO,D,DAL,DD,DE,DFS,DG,DGX,DHI,DHR,DIS,DISCA,DISH,DLTR,DOV,DRI,DTE,DUK,DVA,DVN,DXC,EA,EBAY,ECL,ED,EFX,EIX,EL,EMN,EMR,EOG,EQIX,ES,ETFC,ETN,ETR,EVRG,EW,EXC,EXPD,EXPE,F,FANG,FAST,FB,FBHS,FCX,FDX,FE,FFIV,FIS,FISV,FLIR,FLS,FLT,FMC,FOXA,FTI,FTNT,GD,GE,GILD,GIS,GL,GLW,GM,GOOGL,GPC,GPN,GPS,GRMN,GS,GWW,HAL,HAS,HBAN,HBI,HCA,HD,HES,HFC,HII,HLT,HOG,HOLX,HON,HP,HPE,HPQ,HRB,HRL,HSIC,HSY,HUM,IBM,ICE,IDXX,IEX,IFF,ILMN,INCY,INFO,INTC,INTU,IP,IPG,IPGP,IQV,IR,IRM,ISRG,IT,ITW,IVZ,J,JBHT,JCI,JKHY,JNJ,JNPR,JPM,JWN,K,KEYS,KHC,KLAC,KMB,KMI,KMX,KO,KR,KSS,KSU,L,LB,LDOS,LEG,LEN,LH,LHX,LIN,LKQ,LLY,LMT,LNC,LNT,LOW,LRCX,LUV,LVS,LYB,LYV,M,MA,MAR,MAS,MCD,MCHP,MCK,MCO,MDLZ,MDT,MET,MGM,MHK,MKC,MLM,MMC,MMM,MNST,MO,MOS,MPC,MRK,MRO,MS,MSCI,MSFT,MSI,MTD,MU,MXIM,MYL,NBL,NCLH,NDAQ,NEE,NEM,NFLX,NI,NKE,NLOK,NLSN,NOC,NOV,NOW,NRG,NSC,NTAP,NTRS,NUE,NVDA,NVR,NWL,NWSA,ODFL,OKE,OMC,ORCL,ORLY,OXY,PAYC,PAYX,PCAR,PEG,PEP,PFE,PFG,PG,PGR,PH,PHM,PKG,PKI,PM,PNC,PNR,PNW,PPG,PPL,PRGO,PRU,PSX,PVH,PWR,PXD,PYPL,QCOM,QRVO,RCL,RE,REGN,RHI,RJF,RL,RMD,ROK,ROL,ROP,ROST,RSG,RTN,SBAC,SBUX,SCHW,SEE,SHW,SJM,SLB,SNA,SNPS,SO,SPGI,SRE,STE,STT,STX,STZ,SWK,SWKS,SYF,SYK,SYY,T,TAP,TDG,TEL,TFC,TFX,TGT,TIF,TJX,TMO,TMUS,TPR,TROW,TRV,TSCO,TSN,TTWO,TWTR,TXN,TXT,UAA,UAL,UHS,ULTA,UNH,UNM,UNP,UPS,URI,USB,V,VAR,VFC,VIAC,VLO,VMC,VRSK,VRSN,VRTX,VZ,WAB,WAT,WBA,WDC,WEC,WFC,WHR,WLTW,WM,WMB,WMT,WRB,WRK,WU,WYNN,XEC,XEL,XLNX,XOM,XRAY,XRX,XYL,YUM,ZBH,ZBRA,ZTS]
sym_list = ['A','AAL','AAP','AAPL','ABBV','ABC','ABMD','ABT','ACN','ADBE','ADI','ADM','ADP','ADS','ADSK','AEE','AEP','AES','AFL','AGN','AIG','AIZ','AJG','AKAM','ALB','ALGN','ALK','ALL','ALLE','ALXN','AMAT','AMCR','AMD','AME','AMGN','AMP','AMT','AMZN','ANET','ANSS','ANTM','AON','AOS','APA','APD','APH','APTV','ARNC','ATO','ATVI','AVGO','AVY','AWK','AXP','AZO','BA','BAC','BAX','BBY','BDX','BEN','BIIB','BK','BKNG','BKR','BLK','BLL','BMY','BR','BSX','BWA','C','CAG','CAH','CAT','CB','CBOE','CBRE','CCI','CCL','CDNS','CDW','CE','CERN','CF','CFG','CHD','CHRW','CHTR','CI','CL','CLX','CMA','CMCSA','CME','CMG','CMI','CMS','CNC','CNP','COF','COG','COO','COP','COST','COTY','CPB','CPRI','CPRT','CRM','CSCO','CSX','CTAS','CTL','CTSH','CTXS','CVS','CVX','CXO','D','DAL','DD','DE','DFS','DG','DGX','DHI','DHR','DIS','DISCA','DISH','DLTR','DOV','DRI','DTE','DUK','DVA','DVN','DXC','EA','EBAY','ECL','ED','EFX','EIX','EL','EMN','EMR','EOG','EQIX','ES','ETFC','ETN','ETR','EVRG','EW','EXC','EXPD','EXPE','F','FANG','FAST','FB','FBHS','FCX','FDX','FE','FFIV','FIS','FISV','FLIR','FLS','FLT','FMC','FOXA','FTI','FTNT','GD','GE','GILD','GIS','GL','GLW','GM','GOOGL','GPC','GPN','GPS','GRMN','GS','GWW','HAL','HAS','HBAN','HBI','HCA','HD','HES','HFC','HII','HLT','HOG','HOLX','HON','HP','HPE','HPQ','HRB','HRL','HSIC','HSY','HUM','IBM','ICE','IDXX','IEX','IFF','ILMN','INCY','INFO','INTC','INTU','IP','IPG','IPGP','IQV','IR','IRM','ISRG','IT','ITW','IVZ','J','JBHT','JCI','JKHY','JNJ','JNPR','JPM','JWN','K','KEYS','KHC','KLAC','KMB','KMI','KMX','KO','KR','KSS','KSU','L','LB','LDOS','LEG','LEN','LH','LHX','LIN','LKQ','LLY','LMT','LNC','LNT','LOW','LRCX','LUV','LVS','LYB','LYV','M','MA','MAR','MAS','MCD','MCHP','MCK','MCO','MDLZ','MDT','MET','MGM','MHK','MKC','MLM','MMC','MMM','MNST','MO','MOS','MPC','MRK','MRO','MS','MSCI','MSI','MTD','MU','MXIM','MYL','NBL','NCLH','NDAQ','NEE','NEM','NFLX','NI','NKE','NLOK','NLSN','NOC','NOV','NOW','NRG','NSC','NTAP','NTRS','NUE','NVDA','NVR','NWL','NWSA','ODFL','OKE','OMC','ORCL','ORLY','OXY','PAYC','PAYX','PCAR','PEG','PEP','PFE','PFG','PG','PGR','PH','PHM','PKG','PKI','PM','PNC','PNR','PNW','PPG','PPL','PRGO','PRU','PSX','PVH','PWR','PXD','PYPL','QCOM','QRVO','RCL','RE','REGN','RHI','RJF','RL','RMD','ROK','ROL','ROP','ROST','RSG','RTN','SBAC','SBUX','SCHW','SEE','SHW','SJM','SLB','SNA','SNPS','SO','SPGI','SRE','STE','STT','STX','STZ','SWK','SWKS','SYF','SYK','SYY','T','TAP','TDG','TEL','TFC','TFX','TGT','TIF','TJX','TMO','TMUS','TPR','TROW','TRV','TSCO','TSN','TTWO','TWTR','TXN','TXT','UAA','UAL','UHS','ULTA','UNH','UNM','UNP','UPS','URI','USB','V','VAR','VFC','VIAC','VLO','VMC','VRSK','VRSN','VRTX','VZ','WAB','WAT','WBA','WDC','WEC','WFC','WHR','WLTW','WM','WMB','WMT','WRB','WRK','WU','WYNN','XEC','XEL','XLNX','XOM','XRAY','XRX','XYL','YUM','ZBH','ZBRA','ZTS']
# sym_list = ['A','AAL','AAP']

count = 0
for i in sym_list:
    count += 1
    print("count: ", count)
    j = yf.Ticker(i)
    hist = j.history(period="10y")
    hist['Symbol'] = i
    print(hist.head())
    temp = [hist_final, hist]
    hist_final = pd.concat(temp)
    # print("Tail record:")



hist_final.to_csv("C:/Users/sruja/OneDrive/insights program/insight_project1/hist_final_1min.csv")